services:
  # Core external services.
  # 
  # Postgres database: Required as stateful NS-related services use it for data storage.
  postgres:
    image: postgres:16.9
    container_name: postgres-ns
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: nationstates
      POSTGRES_INITDB_ARGS: "--data-checksums"
      POSTGRES_HOST_AUTH_METHOD: "md5"
      POSTGRES_SHARED_BUFFERS: "256MB"
      POSTGRES_WORK_MEM: "16MB"
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d nationstates"]
      interval: 5s
      timeout: 5s
      retries: 5
  # RabbitMQ: Required as almost all services here use it to communicate between each other.
  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq-ns
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD-SHELL", "rabbitmq-diagnostics ping"]
      interval: 5s
      timeout: 5s
      retries: 5
  # Core internal services
  #
  # Akari: SSE client. Required and used by almost all other NS-related services here.
  akari:
    build: ./Akari
    container_name: akari
    restart: always
    environment:
      NS_USER_AGENT: ${USER_AGENT}
      DATABASE_URL: postgres://postgres:${POSTGRES_PASSWORD}@postgres:5432/nationstates
      RABBITMQ_URL: amqp://rabbitmq:${RABBITMQ_PASSWORD}@rabbitmq:5672
    volumes:
      - ./config:/config
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
  # Optional internal services
  #
  # Bubble: Regional and world activity + RMB webhook.
  bubble:
    build: ./Bubble
    container_name: bubble
    restart: always
    environment:
      NS_USER_AGENT: ${USER_AGENT}
      RABBITMQ_URL: amqp://rabbitmq:${RABBITMQ_PASSWORD}@rabbitmq:5672
    volumes:
      - ./config:/config
    depends_on:
      rabbitmq:
        condition: service_healthy
    profiles:
      - bubble
  # Vanille: Manual recruitment bot.
  vanille:
    build: ./Vanille
    container_name: vanille
    restart: always
    environment:
      NS_USER_AGENT: ${USER_AGENT}
      DISCORD_TOKEN: ${VANILLE_TOKEN}
      DATABASE_URL: postgres://postgres:${POSTGRES_PASSWORD}@postgres:5432/nationstates
      RABBITMQ_URL: amqp://rabbitmq:${RABBITMQ_PASSWORD}@rabbitmq:5672
    volumes:
      - ./config:/config
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    profiles:
      - vanille
  # Crystal: API telegram queuer and recruiter.
  crystal:
    build: ./crystal
    container_name: crystal
    restart: always
    environment:
      NS_USER_AGENT: ${USER_AGENT}
      RABBITMQ_URL: amqp://rabbitmq:${RABBITMQ_PASSWORD}@rabbitmq:5672
    volumes:
      - ./config:/config
    depends_on:
      rabbitmq:
        condition: service_healthy
    profiles:
      - crystal
